# Generated by Django 3.1.7 on 2021-04-05 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ludorecherche', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='add_on',
            options={'verbose_name': 'extension'},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name': 'jeu', 'verbose_name_plural': 'jeux'},
        ),
        migrations.RemoveField(
            model_name='game',
            name='add_ons',
        ),
        migrations.AddField(
            model_name='game',
            name='add_ons',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ludorecherche.add_on'),
        ),
    ]
