# Generated by Django 3.1.7 on 2021-04-07 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ludorecherche', '0004_auto_20210406_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='nom')),
            ],
            options={
                'verbose_name': 'langue',
            },
        ),
        migrations.CreateModel(
            name='PlayingMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='nom')),
            ],
            options={
                'verbose_name': 'type',
            },
        ),
        migrations.CreateModel(
            name='Search_form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='nom')),
                ('player_number', models.IntegerField(blank=True, null=True, verbose_name='nombre de joueur minimum')),
                ('playing_time', models.IntegerField(blank=True, null=True, verbose_name='durée de jeu')),
                ('difficulty', models.CharField(blank=True, max_length=50, null=True, verbose_name='niveau de difficulté')),
                ('designer', models.CharField(blank=True, max_length=200, null=True, verbose_name='name')),
                ('artist', models.CharField(blank=True, max_length=200, null=True, verbose_name='name')),
                ('publisher', models.CharField(blank=True, max_length=200, null=True, verbose_name='name')),
                ('tag', models.CharField(blank=True, max_length=200, null=True, verbose_name='étiquette')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='age',
            field=models.IntegerField(null=True, verbose_name='âge'),
        ),
        migrations.AlterField(
            model_name='add_on',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game', to='ludorecherche.game'),
        ),
        migrations.AddField(
            model_name='game',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='langue', to='ludorecherche.language'),
        ),
        migrations.AddField(
            model_name='game',
            name='playing_mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type', to='ludorecherche.playingmode'),
        ),
    ]
