# Generated by Django 3.1.7 on 2021-04-07 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ludorecherche', '0005_auto_20210407_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_on',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='add_ons', to='ludorecherche.game'),
        ),
    ]
