# Generated by Django 3.1.7 on 2021-04-07 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ludorecherche', '0006_auto_20210407_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_on',
            name='playing_mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='add_type', to='ludorecherche.playingmode', verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='add_on',
            name='artists',
            field=models.ManyToManyField(blank=True, related_name='add_ons', to='ludorecherche.Artist', verbose_name='illustrateur'),
        ),
        migrations.AlterField(
            model_name='add_on',
            name='designers',
            field=models.ManyToManyField(blank=True, related_name='add_ons', to='ludorecherche.Designer', verbose_name='Auteur'),
        ),
        migrations.AlterField(
            model_name='add_on',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='add_ons', to='ludorecherche.game', verbose_name='jeu associé'),
        ),
        migrations.AlterField(
            model_name='add_on',
            name='publishers',
            field=models.ManyToManyField(blank=True, related_name='add_ons', to='ludorecherche.Publisher', verbose_name='éditeur'),
        ),
        migrations.AlterField(
            model_name='game',
            name='artists',
            field=models.ManyToManyField(blank=True, related_name='games', to='ludorecherche.Artist', verbose_name='illustrateur'),
        ),
        migrations.AlterField(
            model_name='game',
            name='by_player',
            field=models.BooleanField(default=False, verbose_name='temps de jeu défini par joueur ?'),
        ),
        migrations.AlterField(
            model_name='game',
            name='designers',
            field=models.ManyToManyField(blank=True, related_name='games', to='ludorecherche.Designer', verbose_name='auteur'),
        ),
        migrations.AlterField(
            model_name='game',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='langue', to='ludorecherche.language', verbose_name='langue'),
        ),
        migrations.AlterField(
            model_name='game',
            name='max_time',
            field=models.IntegerField(null=True, verbose_name='temps de jeu maximum'),
        ),
        migrations.AlterField(
            model_name='game',
            name='playing_mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type', to='ludorecherche.playingmode', verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='game',
            name='publishers',
            field=models.ManyToManyField(blank=True, related_name='games', to='ludorecherche.Publisher', verbose_name='éditeur'),
        ),
    ]
