# Generated by Django 3.1.7 on 2021-04-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludorecherche', '0008_add_on_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_on',
            name='playing_mode',
        ),
        migrations.AddField(
            model_name='add_on',
            name='playing_mode',
            field=models.ManyToManyField(blank=True, related_name='add_type', to='ludorecherche.PlayingMode', verbose_name='type'),
        ),
        migrations.RemoveField(
            model_name='game',
            name='playing_mode',
        ),
        migrations.AddField(
            model_name='game',
            name='playing_mode',
            field=models.ManyToManyField(blank=True, related_name='type', to='ludorecherche.PlayingMode', verbose_name='type'),
        ),
    ]
