# Generated by Django 3.1.7 on 2021-04-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludorecherche', '0012_auto_20210407_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='bgg_link',
            field=models.TextField(blank=True, verbose_name='URL de BGG'),
        ),
        migrations.AlterField(
            model_name='game',
            name='difficulty',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='niveau de difficulté'),
        ),
        migrations.AlterField(
            model_name='game',
            name='max_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='temps de jeu maximum'),
        ),
        migrations.AlterField(
            model_name='game',
            name='picture',
            field=models.TextField(blank=True, verbose_name="URL de l'image"),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_max',
            field=models.IntegerField(blank=True, null=True, verbose_name='nombre de joueurs maximum'),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='nombre de joueurs minimum'),
        ),
        migrations.AlterField(
            model_name='game',
            name='playing_time',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='durée de jeu'),
        ),
        migrations.AlterField(
            model_name='game',
            name='tag',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='étiquette'),
        ),
    ]
