# Generated by Django 3.1.7 on 2021-04-07 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ludorecherche', '0013_auto_20210407_1123'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Search_form',
        ),
    ]
