# Generated by Django 3.1.7 on 2021-04-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludorecherche', '0014_delete_search_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_on',
            name='difficulty',
            field=models.CharField(max_length=50, null=True, verbose_name='niveau de difficulté'),
        ),
        migrations.AlterField(
            model_name='game',
            name='difficulty',
            field=models.CharField(max_length=50, null=True, verbose_name='niveau de difficulté'),
        ),
    ]
