# Generated by Django 3.1.7 on 2021-04-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludorecherche', '0016_auto_20210407_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='nom')),
            ],
            options={
                'verbose_name': 'étiquettes',
            },
        ),
        migrations.RemoveField(
            model_name='game',
            name='tag',
        ),
        migrations.AddField(
            model_name='game',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='games', to='ludorecherche.Tag', verbose_name='étiquettes'),
        ),
    ]
