# Generated by Django 3.1.7 on 2021-04-08 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ludorecherche', '0017_auto_20210407_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Multi_add_on',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='nom')),
                ('player_min', models.IntegerField(blank=True, null=True, verbose_name='nombre de joueur minimum')),
                ('player_max', models.IntegerField(blank=True, null=True, verbose_name='nombre de joueur maximum')),
                ('playing_time', models.CharField(blank=True, max_length=50, null=True, verbose_name='durée de jeu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('picture', models.TextField(blank=True, verbose_name="URL de l'image")),
                ('bgg_link', models.TextField(blank=True, verbose_name='URL de BGG')),
                ('artists', models.ManyToManyField(blank=True, related_name='multi_add_ons', to='ludorecherche.Artist', verbose_name='illustrateur')),
                ('designers', models.ManyToManyField(blank=True, related_name='multi_add_ons', to='ludorecherche.Designer', verbose_name='Auteur')),
                ('difficulty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multi_add_ons', to='ludorecherche.difficulty', verbose_name='difficulté')),
                ('games', models.ManyToManyField(blank=True, related_name='multi_add_ons', to='ludorecherche.Game', verbose_name='jeux associés')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multi_add_langue', to='ludorecherche.language', verbose_name='langue')),
                ('playing_mode', models.ManyToManyField(blank=True, related_name='multi_add_type', to='ludorecherche.PlayingMode', verbose_name='type')),
                ('publishers', models.ManyToManyField(blank=True, related_name='multi_add_ons', to='ludorecherche.Publisher', verbose_name='éditeur')),
            ],
            options={
                'verbose_name': 'extension partagée',
                'verbose_name_plural': 'extensions  partagées',
            },
        ),
    ]
