# Generated by Django 3.1.7 on 2021-04-08 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ludorecherche', '0018_multi_add_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'étiquette'},
        ),
    ]
