# Generated by Django 3.1.7 on 2021-04-09 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludorecherche', '0020_auto_20210409_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_on',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='âge'),
        ),
        migrations.AddField(
            model_name='multi_add_on',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='âge'),
        ),
    ]
