# Generated by Django 3.1.7 on 2021-04-10 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ludorecherche', '0021_auto_20210409_1030'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Add_on',
            new_name='AddOn',
        ),
        migrations.RenameModel(
            old_name='Multi_add_on',
            new_name='MultiAddOn',
        ),
    ]
