# Generated by Django 3.1.7 on 2021-04-11 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ludorecherche', '0022_auto_20210410_2152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playingmode',
            options={'verbose_name': 'mode de jeu', 'verbose_name_plural': 'modes de jeux'},
        ),
    ]
