# Generated by Django 3.1.7 on 2021-04-16 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ludorecherche', '0024_auto_20210416_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='artists',
            field=models.ManyToManyField(blank=True, to='ludorecherche.Artist', verbose_name='illustrateur'),
        ),
        migrations.AlterField(
            model_name='game',
            name='designers',
            field=models.ManyToManyField(blank=True, to='ludorecherche.Designer', verbose_name='Auteur'),
        ),
        migrations.AlterField(
            model_name='game',
            name='difficulty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ludorecherche.difficulty', verbose_name='difficulté'),
        ),
        migrations.AlterField(
            model_name='game',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ludorecherche.language', verbose_name='langue'),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_max',
            field=models.IntegerField(blank=True, null=True, verbose_name='nombre de joueur maximum'),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='nombre de joueur minimum'),
        ),
        migrations.AlterField(
            model_name='game',
            name='playing_mode',
            field=models.ManyToManyField(blank=True, to='ludorecherche.PlayingMode', verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='game',
            name='publishers',
            field=models.ManyToManyField(blank=True, to='ludorecherche.Publisher', verbose_name='éditeur'),
        ),
    ]
