# Generated by Django 3.1.7 on 2021-04-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludorecherche', '0027_background_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='name',
            field=models.CharField(default='name', max_length=200, unique=True, verbose_name='nom'),
            preserve_default=False,
        ),
    ]
