# Generated by Django 3.1.7 on 2021-04-16 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ludorecherche', '0028_theme_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='background',
            options={'verbose_name': 'Interface'},
        ),
        migrations.AlterModelOptions(
            name='theme',
            options={'verbose_name': 'Thème'},
        ),
    ]
