# Generated by Django 3.1.7 on 2021-04-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludorecherche', '0029_auto_20210416_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='advanced_search_button_text',
            field=models.CharField(blank=True, max_length=200, verbose_name='texte du bouton recherche avancée'),
        ),
        migrations.AddField(
            model_name='theme',
            name='advanced_search_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='titre page de recherche avancée'),
        ),
        migrations.AddField(
            model_name='theme',
            name='color_2nd',
            field=models.CharField(blank=True, max_length=200, verbose_name='couleur secondaire'),
        ),
        migrations.AddField(
            model_name='theme',
            name='color_3rd',
            field=models.CharField(blank=True, max_length=200, verbose_name='couleur tertiaire'),
        ),
        migrations.AddField(
            model_name='theme',
            name='color_4th',
            field=models.CharField(blank=True, max_length=200, verbose_name='couleur quaternaire'),
        ),
        migrations.AddField(
            model_name='theme',
            name='color_main',
            field=models.CharField(blank=True, max_length=200, verbose_name='couleur principale'),
        ),
        migrations.AddField(
            model_name='theme',
            name='image_404',
            field=models.CharField(blank=True, max_length=200, verbose_name='image de page 404'),
        ),
        migrations.AddField(
            model_name='theme',
            name='image_500',
            field=models.CharField(blank=True, max_length=200, verbose_name='image de page 500'),
        ),
        migrations.AddField(
            model_name='theme',
            name='index_text',
            field=models.TextField(blank=True, verbose_name='texte Accueil '),
        ),
        migrations.AddField(
            model_name='theme',
            name='index_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='titre accueil'),
        ),
        migrations.AddField(
            model_name='theme',
            name='list_all_title',
            field=models.TextField(blank=True, verbose_name='titre liste globale '),
        ),
        migrations.AddField(
            model_name='theme',
            name='text_404',
            field=models.TextField(blank=True, verbose_name='texte page 404 '),
        ),
        migrations.AddField(
            model_name='theme',
            name='text_500',
            field=models.TextField(blank=True, verbose_name='texte page 500 '),
        ),
        migrations.AddField(
            model_name='theme',
            name='title_404',
            field=models.TextField(blank=True, verbose_name='titre page 404 '),
        ),
        migrations.AddField(
            model_name='theme',
            name='title_500',
            field=models.TextField(blank=True, verbose_name='titre page 404 '),
        ),
        migrations.AlterField(
            model_name='theme',
            name='background_image',
            field=models.CharField(blank=True, max_length=200, verbose_name='image de fond'),
        ),
    ]
