# Generated by Django 3.1.7 on 2021-04-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludorecherche', '0030_auto_20210417_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='list_all_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='titre liste globale '),
        ),
        migrations.AlterField(
            model_name='theme',
            name='title_404',
            field=models.CharField(blank=True, max_length=200, verbose_name='titre page 404 '),
        ),
        migrations.AlterField(
            model_name='theme',
            name='title_500',
            field=models.CharField(blank=True, max_length=200, verbose_name='titre page 404 '),
        ),
    ]
