# Generated by Django 3.1.7 on 2021-04-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludorecherche', '0031_auto_20210417_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='image_404',
            field=models.CharField(blank=True, max_length=200, verbose_name='image de page non trouvé'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='image_500',
            field=models.CharField(blank=True, max_length=200, verbose_name='image de page erreur serveur'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='text_404',
            field=models.TextField(blank=True, verbose_name='texte page non trouvé '),
        ),
        migrations.AlterField(
            model_name='theme',
            name='text_500',
            field=models.TextField(blank=True, verbose_name='texte page erreur serveur '),
        ),
        migrations.AlterField(
            model_name='theme',
            name='title_404',
            field=models.CharField(blank=True, max_length=200, verbose_name='titre page non trouvé '),
        ),
        migrations.AlterField(
            model_name='theme',
            name='title_500',
            field=models.CharField(blank=True, max_length=200, verbose_name='titre page erreur serveur '),
        ),
    ]
