# Generated by Django 3.1.7 on 2021-04-17 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludorecherche', '0032_auto_20210417_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='font_link',
            field=models.CharField(blank=True, max_length=200, verbose_name='nom de la police'),
        ),
        migrations.AddField(
            model_name='theme',
            name='font_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='nom de la police'),
        ),
    ]
