# Generated by Django 3.1.7 on 2021-04-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludorecherche', '0034_auto_20210417_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='empty_query_text',
            field=models.TextField(blank=True, verbose_name='texte requête vide '),
        ),
        migrations.AddField(
            model_name='theme',
            name='query_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='nom de la requête'),
        ),
    ]
