# Generated by Django 3.1.7 on 2021-04-17 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludorecherche', '0035_auto_20210417_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='empty_query_image',
            field=models.CharField(blank=True, max_length=200, verbose_name='image requête vide'),
        ),
    ]
