# Generated by Django 3.1.7 on 2021-04-17 14:18

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ludorecherche', '0036_theme_empty_query_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='color_2nd',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
        migrations.AlterField(
            model_name='theme',
            name='color_3rd',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
        migrations.AlterField(
            model_name='theme',
            name='color_4th',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
        migrations.AlterField(
            model_name='theme',
            name='color_main',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
    ]
