# Generated by Django 3.1.7 on 2021-04-18 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludorecherche', '0037_auto_20210417_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='addon',
            name='english_name',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='nom anglais'),
        ),
        migrations.AddField(
            model_name='game',
            name='english_name',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='nom anglais'),
        ),
        migrations.AddField(
            model_name='multiaddon',
            name='english_name',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='nom anglais'),
        ),
    ]
