# Generated by Django 3.1.7 on 2021-04-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludorecherche', '0039_auto_20210418_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mechanism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='nom')),
            ],
            options={
                'verbose_name': 'mécanique associé',
                'verbose_name_plural': 'mécaniques associés',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='nom')),
            ],
            options={
                'verbose_name': 'Thème associé',
                'verbose_name_plural': 'Thèmes associés',
            },
        ),
        migrations.AddField(
            model_name='game',
            name='mechanism',
            field=models.ManyToManyField(blank=True, related_name='games', to='ludorecherche.Mechanism', verbose_name='mécaniques associées'),
        ),
        migrations.AddField(
            model_name='game',
            name='topic',
            field=models.ManyToManyField(blank=True, related_name='games', to='ludorecherche.Topic', verbose_name='thèmes associés'),
        ),
    ]
