# Generated by Django 3.1.7 on 2021-04-18 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludorecherche', '0040_auto_20210418_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addon',
            name='stock',
            field=models.IntegerField(default=1, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='game',
            name='stock',
            field=models.IntegerField(default=1, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='multiaddon',
            name='stock',
            field=models.IntegerField(default=1, verbose_name='Quantité'),
        ),
    ]
