# Generated by Django 3.1.7 on 2021-05-10 12:32

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ludorecherche', '0041_auto_20210418_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='color_back',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
    ]
