# Generated by Django 3.1.7 on 2021-05-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludorecherche', '0044_auto_20210511_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='addon',
            name='max_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='temps de jeu maximum'),
        ),
        migrations.AddField(
            model_name='multiaddon',
            name='max_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='temps de jeu maximum'),
        ),
    ]
