# Generated by Django 3.1.7 on 2021-05-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_img_url', models.CharField(blank=True, max_length=200, null=True, verbose_name="url d'image locale")),
                ('external_img_url', models.CharField(blank=True, max_length=200, null=True, verbose_name="url d'image externe")),
                ('internal_video_url', models.CharField(blank=True, max_length=200, null=True, verbose_name='url de vidéo interne')),
                ('external_video_url', models.CharField(blank=True, max_length=200, null=True, verbose_name='url de vidéo externe')),
                ('comment', models.TextField(verbose_name="texte de l'article")),
            ],
        ),
    ]
