# Generated by Django 3.1.7 on 2021-05-11 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludoaccueil', '0004_auto_20210511_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='audio_codec',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='codec audio'),
        ),
        migrations.AddField(
            model_name='news',
            name='audio_url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="url de l'audio"),
        ),
    ]
